language: java

sudo: false # run on container-based infrastructure

cache:
  directories:
    - $HOME/.m2/repository/

jdk:
  - openjdk8
  - openjdk11

install: true

services:
  - rabbitmq
  - redis-server

script: mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)